# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: optimize
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.7
# Required by azureml-defaults, installed separately through Conda to
# get a prebuilt version and not require build tools for the install.
- psutil=5.6 #latest

- pip:
  # Required packages for AzureML execution, history, and data preparation.
      - azureml-core
      - azureml-defaults
      - azureml-sdk
      - azureml-contrib-services
      - azureml
      - numpy
      - requests
      - gunicorn
      - flask
      - pyyaml
    